name: Release Firebase
on: [push]
jobs:
  Release-Firebase:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v3
      - name: 'Install submodules'
        run: |
          git submodule init
          git submodule update
      - name: 'Install node modules'
        run: |
          npm i
          cd functions
          npm i
          cd sender-api
          npm i
      - name: 'Create config folder'
        run: mkdir config
      - name: 'Setup Firebase Service Account Key'
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: 'firebaseServiceAccountKey.json'
          json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          dir: '/config'
      - name: 'Deploy'
        run: firebase deploy
      # - name: 'Deploy to firebase'
      #   uses: FirebaseExtended/action-hosting-deploy@v0
      #   with:
      #     repoToken: "${{ secrets.GITHUB_TOKEN }}"
      #     firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}"
      #     projectId: sender-76256
      #     channelId: live
      # - name: Deploy function
      #   uses: sws2apps/firebase-deployment@main #consider using pin for dependabot auto update
      #   with:
      #     function: true
      #     project: 'sender-76256' 
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      # - name: Deploy hosting
      #   uses: sws2apps/firebase-deployment@main #consider using pin for dependabot auto update
      #   with:
      #     hosting: true
      #     project: 'sender-76256' 
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}