name: Release Firebase
on: [push]
jobs:
  Release-Firebase:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v3
      - name: 'Install submodules'
        run: |
          git submodule init
          git submodule update
      - name: 'Install node modules'
        run: |
          npm i
          cd functions
          npm i
          cd sender-api
          npm i
      - name: 'Setup firebase'
        run: |
          mkdir config
          cd config
          touch firebaseServiceAccountKey.json