name: Release Firebase
on: [push]
jobs:
  Release-Firebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git submodule init
          git submodule update
      - run: |
          npm i
          cd functions
          npm i
          cd sender-api
          npm i
          ls
          mkdir config
          cd config
          touch firebaseServiceAccountKey.json
          ls