name: Release Firebase
on: [push]
jobs:
  Release-Firebase:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v3
      - name: 'Install submodules'
        run: |
          git submodule init
          git submodule update
      - name: 'Install node modules'
        run: |
          npm i
          cd functions
          npm i
          cd sender-api
          npm i
      - name: 'Create config folder'
        run: mkdir config
      - name: 'Setup Firebase Service Account Key'
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: 'firebaseServiceAccountKey.json'
          json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          dir: '/config'
      - name: Firebase Deployment
        uses: sws2apps/firebase-deployment@v2.1.0
        with:
          config: 'firebase.json'
          function: true
          hosting: true
          project: 'Sender'
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
