name: Release Firebase
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: git submodule init
      - run: git submodule update
      - run: npm i
      - run: cd functions
      - run: npm i
      - run: cd sender-api
      - run: npm i
      - mkdir: config
      - run: cd config
      - touch: firebaseServiceAccountKey.json
      - run: firebase deploy